### ISSUE TITLE
[bug] Failed to load picture

### ISSUE THREAD

**Issue by timelic** [mubaidr/vite-vue3-chrome-extension#1]
<img width="459" alt="截屏2023-03-04 10 15 28" src="https://user-images.githubusercontent.com/20257354/222870521-e5b057cb-dab4-4bab-b8ec-6d94880bc184.png">

I just clone the template and run command `pnpm dev`, and the vue's logo is broken.

I guess it needs to be placed in public folder?

_My platform and os: chrome, mac_

**Comment by mubaidr** [comment]
Chrome manifest v3 does not allow third party resources, please correct me if am wrong. We need to include all resources within extension package.

**Comment by timelic** [comment]
Oh it's just because the path is wrong.

You can replace the `"./assets/vue.svg"` with `"../assets/vue.svg"` in the template.

**Comment by mubaidr** [comment]
Thanks, updating
