### ISSUE TITLE
hope to add sidepanel support

### ISSUE THREAD

**Issue by minkuan** [mubaidr/vite-vue3-chrome-extension#108]
hope to add sidepanel support to sync  chrome extension capabilities

**Comment by mubaidr** [comment]
This is actually pretty straightforward; you can follow the existing pages (popup or options) example: 

- Clone the contents of popup page directory (`/src/popup` to `/src/side-panel`)
- Add following to `manifest.config.ts`
```ts
  side_panel: {
    default_path: "src/side-panel/index.html",
  },
```
- Add following to `vite.config.ts`
```ts
  {
    dir: 'src/side-panel/pages',
    baseRoute: 'side-panel',
  },
```

This will add a side-panel to your extension with everything supported like tailwind, pages, routes etc
