### ISSUE TITLE
Drop webextension-polyfill support

### ISSUE THREAD

**Issue by baramofme** [mubaidr/vite-vue3-chrome-extension#11]
I read this comment. 
https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-1188822881

That said, MV3 doesn't need [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) at all.

How about drop it?

**Comment by mubaidr** [comment]
Totally missed it. Yes, we can drop it.

Willing to create a pull request?

**Comment by baramofme** [comment]
@mubaidr #12 ready to merge
