### ISSUE TITLE
Running in dev environment, 404

### ISSUE THREAD

**Issue by fuwenjiang1997** [mubaidr/vite-vue3-chrome-extension#119]
git clone project, after install and pnpm run dev:chrome，page is 404

<img width="864" alt="image" src="https://github.com/user-attachments/assets/174a45aa-f4e4-4aa8-bda5-19f1df30db9e">

**Comment by mubaidr** [comment]
You need to load this extension using: chrome://extensions/

Open above page, enable developer mode, then load extension from directory.

**Comment by realrecordzLab** [comment]
> You need to load this extension using: chrome://extensions/
> 
> Open above page, enable developer mode, then load extension from directory.

I have the same problem.  the url http://localhost:5173/__devtools__/ will stay locked on the vue logo, the extension is installed but the http://localhost:5173/ is unreachable. I assume that there is no way to see the UI with the dev mode running?

**Comment by mubaidr** [comment]
> > You need to load this extension using: chrome://extensions/
> > Open above page, enable developer mode, then load extension from directory.
> 
> I have the same problem. the url http://localhost:5173/__devtools__/ will stay locked on the vue logo, the extension is installed but the http://localhost:5173/ is unreachable. I assume that there is no way to see the UI with the dev mode running?

For now, all pages have dedicated vue devtools enabled. 

Dedicated devtools link should also work, but we need to diagnose it.

**Comment by realrecordzLab** [comment]
> > > You need to load this extension using: chrome://extensions/
> > > Open above page, enable developer mode, then load extension from directory.
> > 
> > 
> > I have the same problem. the url http://localhost:5173/__devtools__/ will stay locked on the vue logo, the extension is installed but the http://localhost:5173/ is unreachable. I assume that there is no way to see the UI with the dev mode running?
> 
> For now, all pages have dedicated vue devtools enabled.
> 
> Dedicated devtools link should also work, but we need to diagnose it.

I've reinstalled the extension, now dev server hot reload and vue devtools seems working fine. In my case Chrome was using a previous dist folder and this caused the issue

**Comment by realrecordzLab** [comment]
Not sure why but devtools into the extension window seems not working ?
<img width="1201" alt="Screenshot 2024-12-17 alle 14 17 45" src="https://github.com/user-attachments/assets/f51daead-d8e5-4873-8d5b-0c2eea81801c" />
