### ISSUE TITLE
Build fail after icons are inserted into a template

### ISSUE THREAD

**Issue by realrecordzLab** [mubaidr/vite-vue3-chrome-extension#126]
I'm trying to use the icons included, but the build will fail because the related icons file are not found. 

I've tried to follow the instruction found [here](https://github.com/unplugin/unplugin-icons?tab=readme-ov-file#auto-importing) to insert icons in my app, but without success.

After the build fail the `pnpm build` command will stop working and to make it work again it's necessary to do `npm i` to reinstall the dependencies. Is this a bug or I'm doing something wrong when insert an icon?

**Comment by mubaidr** [comment]
You don't need to install icon packages, it should auto install. But if it is not working you may try to install related iconify package to dev dependencies. 

If it still does not work, please share the code base with me, I will try to help you.

**Comment by realrecordzLab** [comment]
> You don't need to install icon packages, it should auto install. But if it is not working you may try to install related iconify package to dev dependencies.
> 
> If it still does not work, please share the code base with me, I will try to help you.

Ok, I will do another test then come back if the problem still persist. Thank you

**Comment by realrecordzLab** [comment]
@mubaidr here is a sample of the code I have. I've used icones to find the icon then try to import it inside the template but it will not load the icon when the DOM is rendered.

```
        <button 
          class="btn btn-square w-full px-4 py-4 uppercase"
          @click.prevent="openFileDialog(false)"
        >
          Open File Dialog
          <icon-mdi-movie-search />
        </button>
```

At this point I'm not sure if I'm importing the icon into the wrong way

**Comment by realrecordzLab** [comment]
Finally I've found the problem. The `IconResolver` need to be configured with the desired prefix. The default `i` seems not working in my case.

**Comment by mubaidr** [comment]
> Finally I've found the problem. The `IconResolver` need to be configured with the desired prefix. The default `i` seems not working in my case.

Yeahhhhhh... Looking at your code sample above. I was about to mention the same, glad you found it!
