### ISSUE TITLE
Unable to load firefox dist folder in Firefox developers edition

### ISSUE THREAD

**Issue by realrecordzLab** [mubaidr/vite-vue3-chrome-extension#132]
After run the command `pnpm build`, I'm only able to load the unpacked extension in chrome. If I try to install the extension in firefox developers edition I'm unable to select the firefox folder that is created inside the dist folder. Is this problem occurs only to me or is a bug? How I can pack the extension?

**Comment by mubaidr** [comment]
In firefox you select manifest file to load, are sure you are laoding it correct way?

**Comment by realrecordzLab** [comment]
> In firefox you select manifest file to load, are sure you are laoding it correct way?

I'm able to select the manifest file at the moment. The problem is that it will contain invalid keys for firefox.
I'm also getting this error logged, it will not occur in chrome
```
TypeError: can't access property "ready", navigator.serviceWorker is undefined
```

**Comment by mubaidr** [comment]
I just tested the latest build on Firefox, everything works fine!

![Screenshot_20241203_000216](https://github.com/user-attachments/assets/3055027d-7759-4113-a17d-a03e88c92263)
