### ISSUE TITLE
promise error message

### ISSUE THREAD

**Issue by stone89son** [mubaidr/vite-vue3-chrome-extension#15]
I am running pnpm dev in the console with no errors but when I look in the chrome extensions( [console ](chrome://extensions/) )
I see this error. Any ideas on how to fix?
![error_2](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/6795515/24555767-2a6f-4b4c-803f-ac2bba077eac)

**Comment by mubaidr** [comment]
This error is most probably caused by the usage of `webext-bridge`, the latest version has API changes. Make sure you are following correct usage pattern, please

For more information: https://github.com/zikaari/webext-bridge#readme
