### ISSUE TITLE
can you show how to support i18n in this template?

### ISSUE THREAD

**Issue by minkuan** [mubaidr/vite-vue3-chrome-extension#151]
can you show how to support i18n in this template?

**Comment by mubaidr** [comment]
Sure, I will add an example.

**Comment by realrecordzLab** [comment]
> Sure, I will add an example.

I'm looking for the same thing. We can follow the instruction on chrome developers website or there are different steps?

**Comment by mubaidr** [comment]
I have pushed an update (a comprehensive one), which also includes updated config/ setup for `i18n`. You can also check `src/ui/setup/pages/updated` for an example. https://github.com/mubaidr/vite-vue3-browser-extension-v3/commit/fa114dcee867e39288a5338573e7addb5455e96d

**Comment by realrecordzLab** [comment]
> I have pushed an update (a comprehensive one), which also includes updated config/ setup for `i18n`. You can also check `src/ui/setup/pages/updated` for an example. [fa114dc](https://github.com/mubaidr/vite-vue3-browser-extension-v3/commit/fa114dcee867e39288a5338573e7addb5455e96d)

Saw you've added a plugin to achive this. Thank you, I will need to update the extension to have last update for localization. I assume there is no way to use the standard chrome way to achive this without plugins

**Comment by mubaidr** [comment]
I am pretty sure chrome i18n API is usable too, with no additional config. It's just that the vue-18n plugin offers better tooling. 

update: If you want to use chrome i18n feature, just follow the official guide.
