### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/"

### ISSUE THREAD

**Issue by lockevn** [mubaidr/vite-vue3-chrome-extension#157]
Thanks for the great template.

Problem: Chrome always blames about an error of the extensions `[Vue Router warn]: No match found for location with path "/"`

I think it's the way we use `unplugin-vue-router`.
Can you give a hint to fix it?
Or remove `unplugin-vue-router` and use VueRouter manually (I prefer this, to fully control pages)

![image](https://github.com/user-attachments/assets/a3c1461c-407f-4cc0-b7a6-514ed26ad5d4)

**Comment by mubaidr** [comment]
This has been bothering me for quite a sometime now, I will debug this ASAP

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/vite-vue3-browser-extension-v3/commit/fa114dcee867e39288a5338573e7addb5455e96d
