### ISSUE TITLE
After installation in chrome, pages such as popup and option cannot be displayed properly

### ISSUE THREAD

**Issue by yuanye3486** [mubaidr/vite-vue3-chrome-extension#160]
**Describe the bug**

**To Reproduce**
1. pnpm build:chrome
2. install by dist/chrome
3. when open the popup page, it's empty.

**Screenshots**
<img width="85" alt="image" src="https://github.com/user-attachments/assets/a7925fbf-f36e-4b02-8ad5-ddec5c8f3628" />

**Desktop (please complete the following information):**
 - OS: [macos]
 - Browser [Chrome]
 - Version [Commit bc96837]

**Additional context**
Looks like a base path configuration problem：
`ViteConfig.base = IS_DEV
  ? `http://localhost:${ViteConfig.server?.port}/`
  : `/dist/${browser}``

When I changed it like this：
`ViteConfig.base = IS_DEV
  ? `http://localhost:${ViteConfig.server?.port}/`
  : `/``
it worked fine

**Comment by mubaidr** [comment]
This specific piece of code was redundant form some experimentation, removing it fixes the issue. 

P.S. All buils and outputs are only contained in `dist/browser` pattern. Only zip files are created in `dist` directory.
