### ISSUE TITLE
limited to iframe size

### ISSUE THREAD

**Issue by mttzzz** [mubaidr/vite-vue3-chrome-extension#27]
"Hello, I'm creating a button in a content-script with a fixed position. Everything is working great. But I need a modal window to be displayed across the entire screen when this button is clicked. However, I'm limited by the dimensions of the iframe. What should I do?"

**Comment by mubaidr** [comment]
I recommend using the `iframe` for it too. When then button is clicked you can add `css` styles to `.crx-iframe` to make it full screen with absolute position. 

You can see default content script iframe here: 
https://github.com/mubaidr/vite-vue3-chrome-extension-v3/blob/master/src/content-script/index.scss

**Comment by mttzzz** [comment]
thx. this is good idea
