### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at index.js:1:1)

### ISSUE THREAD

**Issue by botshen** [mubaidr/vite-vue3-chrome-extension#28]
<img width="1472" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/5b312f6f-9a9f-4e06-adb7-8942368ee58d">
<img width="1510" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/0b005bb9-0166-41ba-9269-3c8f2d509f60">

Why is this error occurring, here is my repository address:   [botshen/mock-v3](https://github.com/botshen/mock-v3)

Please run  `pnpm i `  `pnpm build`   and then load the extension in chrome then you can see this error message, what is causing this?

**Comment by mubaidr** [comment]
You are trying to use import statements in js file, which is causing issue. Also if you run `pnpm dev` and load extension in chrome, it will display better error messages (with source-maps).

**Comment by botshen** [comment]
> You are trying to use import statements in js file, which is causing issue. Also if you run `pnpm dev` and load extension in chrome, it will display better error messages (with source-maps).

If I run pnpm dev I don't see any error message, my script works fine but after build it prompts this error, I don't know why this is happening.

**Comment by mubaidr** [comment]
You are using imports inside a js file, which I believe gets transpiled during dev process. But when using build it is not processed therefore this error. Consider using npm pakcage for the `ajax-hook`

**Comment by botshen** [comment]
> You are using imports inside a js file, which I believe gets transpiled during dev process. But when using build it is not processed therefore this error. Consider using npm pakcage for the `ajax-hook` 

<img width="1169" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/f1db5620-ec47-4347-9e00-0bab1f5244f4">
I started out using npm, but I switched to importing js when I got this error
'ajax-hook' is imported by src/content-script/inject.ts, but could not be resolved – treating it as an external dependency

**Comment by mubaidr** [comment]
Did you add package?

```bash
pnpm add ajax-hook
```

and then
```bash
pnpm i
```

**Comment by botshen** [comment]
> Did you add package?你添加了包吗？
> 
> ```shell
> pnpm add ajax-hook
> ```
> 
> and then 进而
> 
> ```shell
> pnpm i
> ```

I of course ran the command to add the dependency and this is my package.json
```json
{
  "dependencies": {
    "ajax-hook": "^3.0.1",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4"
  },
  "devDependencies": {
    "@crxjs/vite-plugin": "^2.0.0-beta.18",
    "@iconify-json/mdi": "^1.1.54",
    "@tailwindcss/forms": "^0.5.4",
    "@types/chrome": "^0.0.243",
    "@types/eslint": "^8.44.2",
    "@types/eslint-config-prettier": "^6.11.0",
    "@types/node": "^18.17.3",
    "@types/prettier": "^3.0.0",
    "@typescript-eslint/eslint-plugin": "^6.3.0",
    "@typescript-eslint/parser": "^6.3.0",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/compiler-sfc": "^3.3.4",
    "@vueuse/core": "^10.3.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.46.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-vue": "^9.16.1",
    "postcss": "^8.4.27",
    "prettier": "^3.0.1",
    "prettier-plugin-tailwindcss": "^0.4.1",
    "sass": "^1.64.2",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.1.6",
    "unplugin-auto-import": "^0.16.6",
    "unplugin-icons": "^0.16.5",
    "unplugin-vue-components": "^0.25.1",
    "vite": "^4.4.9",
    "vite-plugin-pages": "^0.31.0",
    "vue-tsc": "^1.8.8",
    "webext-bridge": "^6.0.1"
  },
  "name": "vite-vue3-chrome-extension-v3",
  "overrides": {
    "@crxjs/vite-plugin": "$@crxjs/vite-plugin"
  },
  "pnpm": {
    "overrides": {},
    "peerDependencyRules": {
      "allowAny": [],
      "allowedDeprecatedVersions": {
        "sourcemap-codec": "1.4.8"
      },
      "allowedVersions": {},
      "ignoreMissing": []
    }
  },
  "private": true,
  "scripts": {
    "build": "vite build",
    "dev": "vite",
    "lint": "eslint . --fix --ext js,mjs,cjs,ts,mts,cts,vue",
    "preview": "vite preview"
  },
  "type": "module",
  "version": "0.0.1"
}

```
The above error still exists and I'm struggling with it  🥺

**Comment by botshen** [comment]
Can you help me look at it, I've been struggling with it for days and still no solution, google can't find an answer, thank you!

**Comment by mubaidr** [comment]
I will check it, pls update repo to use npm package of ajax-hook

**Comment by botshen** [comment]
> I will check it, pls update repo to use npm package of ajax-hook

I've updated the repository, please check it for me if you have time, thanks again!

**Comment by mubaidr** [comment]
- You can inject scripts using `manifest.config.js`
OR
- you can import scripts into content script, `vite` will process these too.

https://github.com/botshen/mock-v3/pull/1

**Comment by botshen** [comment]
<img width="1397" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/27942366-3b24-48ae-bf67-539cfe0f0fe3">
<img width="1368" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/b5fac022-e9fa-4775-a66e-0501ad282ace">
After packaging the js or using the import statement, the browser will report an error
