### ISSUE TITLE
[feature request] add some actions to the right click menu

### ISSUE THREAD

**Issue by timelic** [mubaidr/vite-vue3-chrome-extension#3]
Can you add some template code to create custom action in the right-click menu in all tabs?

i've tried the methods in [this](https://developer.chrome.com/docs/extensions/reference/contextMenus/), but I see no new actions in my right-click menu on any websites.

I would be grateful if you could offer some help ❤️

**Comment by mubaidr** [comment]
Add permissions: 

```json
{
  "name": "My extension",
  ...
  "permissions": [
    "contextMenus",
    "activeTab"
  ],
  "icons": {
    "16": "icon-bitty.png"
  },
  ...
}
```
then in your service_worker (i.e. background script), add listner for context menu click:
```ts
chrome.contextMenus.onClicked.addListener((info, tab) => {
  const { menuItemId, selectionText } = info;
  const { id, url } = tab;
  
  console.log({ id, url, menuItemId, selectionText });
});
```

**Comment by timelic** [comment]
I created this [repo](https://github.com/timelic/right-click-menu-test) to test the code (in the latest commit). However, when I loaded this dev extension into Chrome, nothing seemed to happen, and no new item appeared in my right-click menu.

**Comment by mubaidr** [comment]
> Add permissions:
> 
> ```json
> {
>   "name": "My extension",
>   ...
>   "permissions": [
>     "contextMenus",
>     "activeTab"
>   ],
>   "icons": {
>     "16": "icon-bitty.png"
>   },
>   ...
> }
> ```
> 
> then in your service_worker (i.e. background script), add listner for context menu click:
> 
> ```ts
> chrome.contextMenus.onClicked.addListener((info, tab) => {
>   const { menuItemId, selectionText } = info;
>   const { id, url } = tab;
>   
>   console.log({ id, url, menuItemId, selectionText });
> });
> ```

This just add required permissions and event listeners to the extension. You need to actually create a context menu when installed, e.g. 

```ts
chrome.runtime.onInstalled.addListener(function() {
    chrome.contextMenus.create({
        "title": 'My context Menu"',
        "contexts": ["page"],
        "id": "myContextMenuId"
    });
});
```

More details about context menu API here: https://developer.chrome.com/docs/extensions/reference/contextMenus/#type-ContextType

**Comment by timelic** [comment]
This just what I need! Thanks for you help🥰
