### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at inject.ts.js:1:1)

### ISSUE THREAD

**Issue by botshen** [mubaidr/vite-vue3-chrome-extension#30]
<img width="1368" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/c9e2b8fe-2bf7-4647-b2d1-6b73239fbb86">
<img width="1397" alt="image" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/33440355/c9e193ee-df44-43e8-a8b0-6956e4b7e5db">
After packaging the js or using the import statement, the browser will report an error

**Comment by mubaidr** [comment]
I just tested by building the extension and loading it in chrome, there is no error:
https://github.com/mubaidr/vite-vue3-chrome-extension-v3/issues/28#issuecomment-1686613222

**Comment by botshen** [comment]
Thank you. It's fixed.
