### ISSUE TITLE
I want to use vue-18n in this project. However there is an error. Can you give me some solution?

### ISSUE THREAD

**Issue by 14790897** [mubaidr/vite-vue3-chrome-extension#36]
vue-i18n.js?v=9913f811:2570 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".

**Comment by mubaidr** [comment]
Please visit this link for information how to set permissions: https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/
