### ISSUE TITLE
Chrome V3 Refused to execute inline script ...

### ISSUE THREAD

**Issue by ccc469** [mubaidr/vite-vue3-chrome-extension#37]
Hi, 

thank you very much for providing a great Chrome plugin template. This is when I opened a new window using the V3 version through` [chrome.tabs.create]` and executed a JavaScript code, the console encountered an error as follows:   

![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/27529250/a029ecde-cfff-4a1c-ab37-1d8de5bd3562)

After trying, I still cannot solve this problem until now...
Can you help me solve this problem? Thank you 🙏

**Comment by mubaidr** [comment]
This is security measures by chrome, please visit this link how to set permissions: https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/
