### ISSUE TITLE
Question: image paths inside vue components

### ISSUE THREAD

**Issue by feliperaul** [mubaidr/vite-vue3-chrome-extension#38]
First of all, great template!

Question: instead of relative image paths like

`<img src="../../assets/vite.svg" />`

Would it be possible to use the alias defined in `vite.config.ts`?

`<img src="src/assets/vite.svg" />`

It's not working with the current setup.

**Comment by mubaidr** [comment]
Sorry for the delayed repsonse, vite config needed update, please check latest config, specifically this: 
https://github.com/mubaidr/vite-vue3-chrome-extension-v3/blob/458c3ff554b01e5062d634422a000923e12ae4d3/vite.config.ts#L17
