### ISSUE TITLE
content-script does not use iframe, style issue

### ISSUE THREAD

**Issue by wumingluren** [mubaidr/vite-vue3-chrome-extension#41]
content-script/index.ts code
```
import { createApp } from 'vue'
import App from './content/app.vue'
import './index.scss'

const container = document.createElement('div')
container.id = 'test' 
container.className = 'test' 

const root = document.createElement('div')
root.id = 'test-app'


const shadowDOM = container.attachShadow?.({ mode: 'open' }) || container
shadowDOM.appendChild(root)


document.body.appendChild(container)


const app = createApp(App)

app.config.globalProperties.$app = {
  context: '',
}


app.provide('app', app.config.globalProperties.$app)


app.mount(root)

```
content-script/content/app.vue
```
<template>
  <div class="testqwe">
    <div
      class="floating-text"
      style="font-size: 50px; color: red"
    >
      test
    </div>
  </div>
</template>
<style lang="scss">
.floating-text {
 position: fixed;
  top: 50%;
   left: 50%;
  transform: translate(-50%, -50%);
  font-size: 24px;
  font-weight: bold;
   padding: 10px;
   background-color: rgba(0, 0, 0, 0.5);
   color: white;
   border-radius: 5px;
}
.testqwe {
  background-color: #ffffff;
}
```
Neither the styles in index.scss nor the styles in style lang='scss' are taking effect, only the inline styles mentioned above are working. Why is this happening? 
I want to create a floating content that appears in the middle of the page, without using an iframe.

**Comment by mubaidr** [comment]
You are using shadow dom, I don't think you can directly style these. Please read more here: 

https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/

**Comment by wumingluren** [comment]
> You are using shadow dom, I don't think you can directly style these. Please read more here:
> 
> https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/

Thanks for the answer, deleting shadow dom solved the problem.
