### ISSUE TITLE
When my plugin opens a local html page, it can't find the js file in the same directory as the page?

### ISSUE THREAD

**Issue by 14790897** [mubaidr/vite-vue3-chrome-extension#43]

**Comment by mubaidr** [comment]
Opening local html page means install/ update page?
Can you please share a reproduceable repo. I will be able to help quickly. Thanks

**Comment by 14790897** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';">

  <title>Word Cloud</title>
</head>
<body>
  <div id="app"></div>
  <script src="script.js"></script>
</body>
</html>
```

**Comment by 14790897** [comment]
It can't find script.js in the same directory.

**Comment by 14790897** [comment]
```
 const url = chrome.runtime.getURL('src/components/wordcloud.html');
  console.log('URL:', url); 
  chrome.tabs.create({ url: url }, (tab) => {
    if (chrome.runtime.lastError) {
      console.error(chrome.runtime.lastError);  
    } else {
      console.log('Tab created:', tab);  
    }
  });

**Comment by mubaidr** [comment]
You should try using relative path for script, i.e. `./script.js`

**Comment by 14790897** [comment]
I was wrong before, the error is not about not finding the file but about the following error             
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/121866954/8722f638-4b39-4c49-82d6-e4fadfc866fa)

**Comment by mubaidr** [comment]
You are trying to use import statements inside static html page and scripts, which are not supported. Either add bundler (vite) processing for install and upgrade page or use simple scripts.
