### ISSUE TITLE
Add vue devtools vite plugin

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/vite-vue3-chrome-extension#53]
vite-plugin-vue-devtools: https://devtools-next.vuejs.org/guide/vite-plugin

**Comment by mubaidr** [comment]
Investigate why `vue-devtools` breaks webpage styles. maybe related to: https://github.com/mubaidr/vite-vue3-chrome-extension-v3/pull/51?

**Comment by ultimateshadsform** [comment]
It would be nice if we could just exclude instead of using a prefix.

**Comment by mubaidr** [comment]
We have to solve this tailwind issue either way. So I think this is worth the effort?

**Comment by ultimateshadsform** [comment]
> We have to solve this tailwind issue either way. So I think this is worth the effort?

Yeah. I think it's worth the effort. Maybe try prefix first just to see if it's the root cause and then use exclude if it works.

But if you open the devtools page you can see an error with inject.js. I think that may be the cause of issue.

**Comment by ultimateshadsform** [comment]
> We have to solve this tailwind issue either way. So I think this is worth the effort?

I just checked by removing tailwind. No the issue is not tailwind.

It must be the inject.js problem that is causing it because it can't load properly.

**Comment by ultimateshadsform** [comment]
This is the cause:
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/f5357474-0552-4d65-a2e5-bf039143da6f)

**Comment by mubaidr** [comment]
> This is the cause: ![image](https://private-user-images.githubusercontent.com/151234273/296051942-f5357474-0552-4d65-a2e5-bf039143da6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzQyODgsIm5iZiI6MTcwNTAzMzk4OCwicGF0aCI6Ii8xNTEyMzQyNzMvMjk2MDUxOTQyLWY1MzU3NDc0LTA1NTItNGQ2NS1hMmU1LWJmMDM5MTQzZGE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNDMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGMwMTdhODdhMWI0MThjMmEwZWYzNTM0NTY1MmUwOTNkMzA0NTkxMjFiYzlkNjE5MGI0M2RhNjY1NTM5NTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LRKMBOj5qoAyNKBQML9SKnUbAxvIjTKt9kzgJh4gQ-k)
> 
> ```
> Denying load of chrome-extension://pbcpfbcibpcbfbmddogfhcijfpboeaaf/inject.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> invalid/:1 
>         
>         
>        Failed to load resource: net::ERR_FAILED
> favicon.svg:1 
>         
>         
>        Failed to load resource: the server responded with a status of 404 (Not Found)
> ```

Damn. You have already reported and I forgot about that.

**Comment by mubaidr** [comment]
I think this can be fixed by adding this script to web accessible content list in manifest file.
Let try!

**Comment by mubaidr** [comment]
update: dev tools seem to load fine when opened in new tab, but does not work when opened in extension pages. 
![Screenshot_20240112_141418](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/2222702/1bb2452f-5e19-4178-8927-71be5d3ec113)

**Comment by mubaidr** [comment]
> This is the cause: ![image](https://private-user-images.githubusercontent.com/151234273/296051942-f5357474-0552-4d65-a2e5-bf039143da6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTMzOTQsIm5iZiI6MTcwNTA1MzA5NCwicGF0aCI6Ii8xNTEyMzQyNzMvMjk2MDUxOTQyLWY1MzU3NDc0LTA1NTItNGQ2NS1hMmU1LWJmMDM5MTQzZGE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwOTUxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTg2NTEyZTJkNjc0ZTY4NjU0MDBmNDY5NmNlMjk0NDhkZTM4YWYwMGFjZjVjMjcwMTE1NmRiMmY2MjBmNzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k_rh7CHkjIQTezkVlsOf3YX7K6xtHTARuDmp1uPBzMk)
> 
> ```
> Denying load of chrome-extension://pbcpfbcibpcbfbmddogfhcijfpboeaaf/inject.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> invalid/:1 
>         
>         
>        Failed to load resource: net::ERR_FAILED
> favicon.svg:1 
>         
>         
>        Failed to load resource: the server responded with a status of 404 (Not Found)
> ```

I donot see any error like this, can you please with latest repo.

**Comment by ultimateshadsform** [comment]
Doesn't work. Same error. I'm using latest version of Chrome. 
![image](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/151234273/24681a8f-c8b0-4df3-a9a4-a98db6b598dd)

**Comment by ultimateshadsform** [comment]
Oh sorry. Yeah. The inject.js can be ignored. It must be some other issue for me.
