### ISSUE TITLE
I use Elementplus with autoImport but get typescript error，how to resolve

### ISSUE THREAD

**Issue by feixia666** [mubaidr/vite-vue3-chrome-extension#7]
![impicture_20230413_102726](https://user-images.githubusercontent.com/37666117/231631795-82ce1187-8404-422f-ae30-f7b7c4cd3e18.png)
![impicture_20230413_104302](https://user-images.githubusercontent.com/37666117/231634375-700ea409-70a4-46ba-b41d-9878336a72d5.png)

**Comment by mubaidr** [comment]
Please share error message in English, I maybe able to help

**Comment by feixia666** [comment]
> Please share error message in English, I maybe able to help

Argument of type '{ modelValue: string; class: string; type: string; placeholder: string; }' is not assignable to parameter of type 'App<any> & Partial<{ readonly type: string; readonly modelValue: EpPropMergeType<(new (...args: any[]) => string | number) | (() => string | number | null | undefined) | ((new (...args: any[]) => string | number) | (() => string | number | null | undefined))[], unknown, unknown>; ... 12 more ...; readonly inputStyle...'.
  Type '{ modelValue: string; class: string; type: string; placeholder: string; }' is missing the following properties from type 'App<any>': version, config, use, mixin, and 11 more.ts(2345)
![impicture_20230413_204121](https://user-images.githubusercontent.com/37666117/231761596-1d0bf14e-41bf-49f3-be51-c3ebfc961cb0.png)
