### ISSUE TITLE
it seems like extendRoutes has been removed in Vue Router 4.x.

### ISSUE THREAD

**Issue by GGLEWO** [mubaidr/vite-vue3-chrome-extension#70]
![36b48896e1a49f54180ecabfe7db414](https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/43397792/32e3c0a5-1ace-4bc6-9611-fe124e47b01c)

**Comment by mubaidr** [comment]
Thanks for reporting. I will check

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/vite-vue3-chrome-extension-v3/commit/5063d2d1c943e29cd61c41aa71b01881e9e0dcb4
