### ISSUE TITLE
[Bug] Module source URI is malformed: Firefox

### ISSUE THREAD

**Issue by IgorFZ** [mubaidr/vite-vue3-chrome-extension#82]
Hello everyone,

I’ve been using this template in one of my recent projects, and the extension works perfectly in Google Chrome. However, when trying to use it in Firefox, all the URIs are not found.

When trying to use the extension or reload it, the following error occurs:

```
Module source URI is malformed: “moz-extension://0c3d4b14-63ba-4826-a42f-c2d7889b998e/src/setup/..%5C..%5Cassets/setup--DyKxmCl.js”. index.html:15:76
````

My `index.html`:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      rel="icon"
      type="image/svg+xml"
      href="/vite.svg"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title><%= HTML_TITLE %></title>
    <script type="module" crossorigin src="..\..\assets/setup--DyKxmCl.js"></script>
    <link rel="modulepreload" crossorigin href="..\..\assets/generated-pages_id_~pages-Db5MSHDC.js">
    <link rel="stylesheet" crossorigin href="..\..\assets/generated-pages_id_~pages-CabCv88O.css">
  </head>
  <body>
    <div id="app"></div>

  </body>
</html>
```

I’ve checked the existence of the files, and yes, they do exist in the `dist/firefox/assets`,  directory. Has anyone encountered this issue before?

**Comment by IgorFZ** [comment]
If you modify `index.html` after the build to:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      rel="icon"
      type="image/svg+xml"
      href="/vite.svg"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title><%= HTML_TITLE %></title>
    <script type="module" crossorigin src="../../assets/setup--DyKxmCl.js"></script>
    <link rel="modulepreload" crossorigin href="../../assets/generated-pages_id_~pages-Db5MSHDC.js">
    <link rel="stylesheet" crossorigin href="../../assets/generated-pages_id_~pages-CabCv88O.css">
  </head>
  <body>
    <div id="app"></div>

  </body>
</html>

```

This works, but what changes do I need to make in the Vite build configuration to fix this issue automatically?

**Comment by mubaidr** [comment]
I think I know the issue. Will try a fix later today. If everything goes well. I will update the repo.

**Comment by IgorFZ** [comment]
The error is related to `relative` being used on Windows, which results in backslashes `(\)` in the paths.

This code solves the problem:

````ts
// vite.config.ts
{
    name: 'assets-rewrite',
    enforce: 'post',
    apply: 'build',
    transformIndexHtml(html, { path }) {
        const assetsPath = relative(dirname(path), '/assets').replace(/\\/g, '/');
        return html.replace(/"\/assets\//g, `"${assetsPath}/`);
    },
},
````

I'll keep this issue open for now in case there's a better way to handle this situation.

**Comment by mubaidr** [comment]
You are right, this is the solution. 

Are you willing to open a pull request?

**Comment by IgorFZ** [comment]
Yeah, I'll open a pull request soon.

**Comment by mubaidr** [comment]
Awesome, looking forward to it!

**Comment by mubaidr** [comment]
https://github.com/mubaidr/vite-vue3-browser-extension-v3/pull/83
